/**
 * dsh-alert-sounds — 构建脚本
 *
 * 产物两个，都进 lib/（**lib/ 必须入库**：用户 `dsh plugin add <git 地址>` 装的时候不跑构建）：
 *   1. lib/index.js  —— 宿主半边：src/host.js 原文 + 生成头注释；
 *   2. lib/client.js —— 浏览器半边：src/client.js 原文包进
 *      `window.__ModuleLoader__.load({ id, factory })` 的经典脚本 bundle。
 *      id **必须**等于 package.json 的 name（dsh-client-modules 按 loader 条目的包名解析
 *      注册 ID，写错会 "loaded without registering"）。
 *
 * 锚点替换（都在 src/client.js 里）：
 *   `/*__VERSION__*\/ '0.0.0'` → package.json 的 version
 *   `/*__PANEL__*\/ ''`         → src/panel.js 原文（与 client.js 同一模块作用域）
 *
 * 用法：node scripts/build.mjs
 */
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const LIB = join(ROOT, 'lib')
const MANIFEST = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'))
const PLUGIN_ID = MANIFEST.name
const VERSION_ANCHOR = "/*__VERSION__*/ '0.0.0'"
const PANEL_ANCHOR = "/*__PANEL__*/ ''"

/** 读一个源文件，缺失直接报错（不静默产出半个产物）。 */
function readSource(relative) {
  const file = join(ROOT, relative)
  try {
    return readFileSync(file, 'utf8')
  } catch (error) {
    throw new Error(`构建失败：读不到 ${relative}（${error.message}）`)
  }
}

let clientSource = readSource('src/client.js')

/* ---- 版本号注入 ---- */
if (!clientSource.includes(VERSION_ANCHOR)) {
  throw new Error(`构建失败：src/client.js 里找不到版本锚点 ${VERSION_ANCHOR}`)
}
clientSource = clientSource.replace(VERSION_ANCHOR, () => JSON.stringify(MANIFEST.version))

/* ---- 设置页/浮条（src/panel.js）内联 ----
 * 两者共用同一个模块作用域，所以面板能直接用 settings / t / VERSION / createToastStore 等。 */
if (!clientSource.includes(PANEL_ANCHOR)) {
  throw new Error(`构建失败：src/client.js 里找不到设置页锚点 ${PANEL_ANCHOR}`)
}
clientSource = clientSource.replace(PANEL_ANCHOR, () => readSource('src/panel.js').trim())

/* ---- require 白名单 ----
 * 浏览器半边原则上不做模块解析：`dsh.client.inject` 是空的，factory 的 require 只服务
 * 平台外部模块。React 正是 DSH 模块加载器提供的平台外部模块（官方设置页与
 * dsh-status-rotator / 上游 dsh-alert-sound 都这么拿），所以**只放行 require('react')**。 */
const REQUIRE_ALLOWED = /^require\s*\(\s*(['"])react\1\s*\)$/
const requireCalls = [...clientSource.matchAll(/(^|[^.\w])(require\s*\([^)]*\))/gm)].map((m) => m[2].trim())
const offending = requireCalls.filter((text) => !REQUIRE_ALLOWED.test(text))
if (offending.length > 0) {
  throw new Error(`构建失败：src/client.js / src/panel.js 里出现了不允许的 require()：${offending.join('、')}（只允许 require('react')）`)
}

/* ---- 改名残留闸门 ----
 * 上游包名/存储键如果漏改，最坏的情况是**两个插件共用设置**或 loader id 撞车。
 * 注意只查「作为字符串字面量出现」的形态（带引号）：注释与致谢里合法地写着上游名字
 * （"本文件是 @machine-126/dsh-alert-sound 的派生作品"、GitHub 链接），那些必须保留。 */
const FORBIDDEN = [
  `"@machine-126/dsh-alert-sound"`,
  `'@machine-126/dsh-alert-sound'`,
  `"dsh-alert-sound.v1"`,
  `'dsh-alert-sound.v1'`,
  `"dsh-alert-sound.custom.v1"`,
  `'dsh-alert-sound.custom.v1'`,
  `"dsh-alert-sound"`,
  `'dsh-alert-sound'`,
]
const leftovers = FORBIDDEN.filter((needle) => clientSource.includes(needle))
if (leftovers.length > 0) {
  throw new Error(`构建失败：改名没做干净，仍残留上游标识符：${leftovers.join('、')}（跑 npm run rename 或手工修正）`)
}

const wrapped = [
  '// Generated by scripts/build.mjs from src/client.js + src/panel.js — do not edit directly.',
  `window.__ModuleLoader__.load({ id: ${JSON.stringify(PLUGIN_ID)}, factory: (require) => {`,
  "'use strict';",
  'var module = { exports: {} }; var exports = module.exports;',
  clientSource,
  'return module.exports;',
  '} });',
  '',
].join('\n')

const hostSource = [
  '// Generated by scripts/build.mjs from src/host.js — do not edit directly.',
  readSource('src/host.js').trim(),
  '',
].join('\n')

rmSync(LIB, { recursive: true, force: true })
mkdirSync(LIB, { recursive: true })
writeFileSync(join(LIB, 'index.js'), hostSource)
writeFileSync(join(LIB, 'client.js'), wrapped)

/* ---- 产物自检：形态错了就别让脏产物落地 ---- */
const hasLiteral = (text) => wrapped.includes(`'${text}'`) || wrapped.includes(`"${text}"`)
const problems = []
if (!wrapped.includes(`window.__ModuleLoader__.load({ id: ${JSON.stringify(PLUGIN_ID)}`)) problems.push('bundle id 与包名不一致')
if (!wrapped.includes('return module.exports;')) problems.push('bundle 缺少 module.exports 返回')
if (wrapped.includes(VERSION_ANCHOR) || wrapped.includes(PANEL_ANCHOR)) problems.push('锚点没被替换干净')
if (!wrapped.includes(`const VERSION = ${JSON.stringify(MANIFEST.version)}`)) problems.push('版本号没有注入（锚点替换失败）')
if (!hasLiteral('settings.section')) problems.push('设置页没有内联（panel 锚点替换失败）')
if (!hasLiteral('shell.overlay')) problems.push('浮条 overlay 没有注册')
if (!wrapped.includes('createToastStore')) problems.push('浮条存储没有进 bundle')
if (!wrapped.includes('SettingsPanel') || !wrapped.includes('AlertToast')) problems.push('panel.js 没有内联（找不到 SettingsPanel / AlertToast）')
if (problems.length > 0) {
  throw new Error(`构建产物自检失败：\n  - ${problems.join('\n  - ')}`)
}

const clientBytes = Buffer.byteLength(wrapped)
console.log(`build OK → lib/index.js（宿主占位）、lib/client.js（${(clientBytes / 1024).toFixed(1)} KB, id=${PLUGIN_ID}, v${MANIFEST.version}）`)
